### ISSUE TITLE
TileEditor pictureBoxBrowser needs to be resized

### ISSUE THREAD

**Issue by mgiambrone** [huguesjohnson/MDLib#3]
Looking at the Tile set for the main font of Phantasy Star 3 the tileset gets cut off and I can't tell if it goes further
![image](https://user-images.githubusercontent.com/11039710/198353609-5a55973f-f1d9-4720-8da8-62f86e6ea20a.png)

**Comment by huguesjohnson** [comment]
This is odd. The image box is set to a hard-coded 384x128. The tiles themselves are 8x8 but are scaled into 16x16 squares for readability. There are 24 columns drawn which is also hard-coded. 24x16=384 so it should all fit. Based on that screenshot it's drawing more than 24 tiles in a row which is odd because that number is hard-coded. So the problem looks like it's drawing more tiles in a row than it's supposed to.

**Comment by mgiambrone** [comment]
> This is odd. The image box is set to a hard-coded 384x128. The tiles themselves are 8x8 but are scaled into 16x16 squares for readability. There are 24 columns drawn which is also hard-coded. 24x16=384 so it should all fit. Based on that screenshot it's drawing more than 24 tiles in a row which is odd because that number is hard-coded. So the problem looks like it's drawing more tiles in a row than it's supposed to.

Maybe because Aridia is using a different version? Not sure what version of the source code you are looking at but Aridia is showing TileEditor 1.3 and this github version shows 1.1

**Comment by huguesjohnson** [comment]
Archiving this repo - closing open issues along the way. Sorry I didn't address this issue, this is not a project I've worked on for a while or plan to work on again.
